//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : TestDB
	/// Data Source    : localhost
	/// Server Version : 9.3.2
	/// </summary>
	public partial class TestDBDB : LinqToDB.Data.DataConnection
	{
		public ITable<user> users { get { return this.GetTable<user>(); } }

		public TestDBDB()
		{
		}

		public TestDBDB(string configuration)
			: base(configuration)
		{
		}
	}

	[Table(Schema="public", Name="users")]
	public partial class user
	{
		[Identity          ] public int  id   { get; set; } // integer
		[Column,   Nullable] public int? code { get; set; } // integer
	}
}
